wandb:
  dry_run: False
  project_name: "longi_reg"
  task: "registration_long"
  entity: "ge29jil-technical-university-of-munich"

data:
  feature_key: attn_cls
  #unregistered no aiag patch 8
  train_path: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/extracted_features/no_aiag_8/train.pt"
  dev_path: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/extracted_features/no_aiag_8/dev.pt"
  test_path: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/extracted_features/no_aiag_8/test.pt" 

  #json for reg and unreg
  train_json: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/data/registered_datasets/train.json"
  dev_json: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/data/registered_datasets/dev.json"
  test_json: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/data/registered_datasets/test.json"
  

  max_followup: 6
  num_classes: 1


test:
  ckpt_path: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/longi_model/checkpoints/easy-butterfly-541/best_auc"

training:
  batch_size: 128
  epochs: 300
  early_stopping_patience: 50
  early_stopping_min_delta: 0.0001
  seed: 0
  use_amp: True
  dtype: bfloat16
  num_workers: 0
  dev_num_workers: 0
  sampler: "deterministic_present" 
  minority_patients_per_batch: 6
  shuffle: False 

  #use_scr: False
  #scr_weight: 0.0

model:
  input_dim: 2376 #1584 #cls 792
  hidden_dim: 256 #512 | 256 | 128 | 64 
  n_heads: 4
  n_layers: 2
  pooling: "attn"   # "last" | "mean" | "max" | "attn" | "mean_max"
  max_followup: 6
  dropout: 0.5
  use_difference: True 
 
optimizer:
  peak_lr: 5e-5 #1e-4
  weight_decay: 0.05
  lr_scheduler: "cosine"

log:
  output_dir: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/longi_model/checkpoints"
  log_at_these_steps: 50
  ckpt_best: "best_auc"