defaults:
  - base_config
  - _self_

wandb:
    dry_run: False
    project_name: "longi-jax"
    task: "survival"
    entity: "mri-ai-lab"

data:
    dataset_file: "/dss/dssmcmlfs01/pn73mu/pn73mu-dss-0000/datasets/big_nodule_nlst/dataset_jsons/nlst_25_metadata.json"
    dataset_file_100: "/dss/dssmcmlfs01/pn73mu/pn73mu-dss-0000/datasets/big_nodule_nlst/dataset_jsons/nlst_25_metadata.json"
    slice_thickness_threshold: 2.5
    max_followup: 6
    num_classes: 1
    assign_splits: True
    use_thinnest_cut: True
    corrupted_paths: "./files/corrupted_img_paths.pkl"
    google_splits_filename: "./files/Shetty_et_al(Google)_data_splits.p"
    data_root: "/pool/data/lung/NLST/npy/"
    monai_dict_train: "/nlst_data/train_longi.json"
    monai_dict_dev: "/nlst_data/dev_longi.json"
    monai_dict_test: "/nlst_data/test_longi.json"
    max_train_len: 24000
    img_size: [160, 240, 128]


training:
    dtype: bfloat16
    mask_ratio: 0.5
    seed: 0
    num_workers: 10
    dev_num_workers: 6
    test_num_workers: 1
    prefetch_factor: 10
    dev_prefetch_factor: 4
    shuffle: True
    epochs: 50
    batch_size: 4
    to_checkpoint: False
    sampler: "stratified"
    underrepresented_weight: 14
    minority_samples_per_batch: 1
    freeze_encoder: True
    freeze_mha: True

optimizer:
    lr_scheduler: onecycle
    peak_lr: 8e-6
    init_lr: 8e-6
    end_lr: 8e-6
    warmup_epochs: 0

attention:
    heads: 4
    use_cls: True
    use_mean_token: False

loss:
    sw: 10
    aw: 1

log:
    use_checkpoint: True
    ckpt_loc: "/nlst_data/checkpoints/longivity/"
    ckpt_load_loc: "/nlst_data/checkpoints/lungevity/"
    mae_ckpt_load: 'vit-last'
    mae_use_checkpoint: 'test'
    ckpt_best: 'vit'
    ckpt_last: 'vit-last'
    ckpt_load: 'vit'
    checkpoint_at_epoch: 2
    log_at_these_steps: 500
    log_scans_at_these_epochs: 2
    finetuned_use_checkpoint: 'silver-mountain-94'
    finetuned_ckpt_load: 'vit'
    continue_use_checkpoint: 'test'
    continue_log_ckpt_load: 'test'
    num_predictions: 20
    pretrained_model_type: 'finetuned'

model:
    patch_size: 16
    mlp_hidden_dim: 768
    enc_dim: 768
    dec_dim: 768
    dropout_rate: 0.1
    enc_heads: 12
    enc_depth: 12
    dec_heads: 6
    dec_depth: 4
    in_chans: 1
    rng: 24
    fusion_layer: True

longitudinal:
    model: "transformer"
    rnn_hidden_dim: 768
    rnn_cell: "simple"
    blocks: 6
    heads: 6
    bidirectional: False
    dropout_rate: 0.1

transform:
    train_tf:
        LoadImaged:
            keys: ['image0', 'image1', 'image2']
        EnsureChannelFirstd:
            keys: ['image0', 'image1', 'image2']
        Resized:
            keys: ['image0', 'image1', 'image2']
            mode: ["trilinear", "trilinear", "trilinear"]
            spatial_size: [160, 240, 128]
        ToDeviced:
            keys: ['image0', 'image1', 'image2']
            device: "cuda"
        RandFlipd_1:
            keys: ['image0', 'image1', 'image2']
            prob: 0.33
            spatial_axis: 0
        RandFlipd_2:
            keys: ['image0', 'image1', 'image2']
            prob: 0.33
            spatial_axis: 1
        RandFlipd_3:
            keys: ['image0', 'image1', 'image2']
            prob: 0.33
            spatial_axis: 2
        RandRotated:
            keys: ['image0', 'image1', 'image2']
            prob: 0.5
            range_x: 0.2
            range_y: 0.2
            range_z: 0.2
            mode: ['bilinear', 'bilinear', 'bilinear']
        RandHistogramShiftd:
            keys: ['image0', 'image1', 'image2']
            prob: 0.33
            num_control_points: [5,8]
        RandGaussianSharpend:
            keys: ['image0', 'image1', 'image2']
            sigma1_x: [0.1,0.5]
            sigma1_y: [0.1,0.5]
            sigma1_z: [0.1,0.5]
            sigma2_x: 0.3
            sigma2_y: 0.3
            sigma2_z: 0.3
            prob: 0.33
            alpha: [1.5, 10]
        RandGaussianNoised:
            keys: ['image0', 'image1', 'image2']
            prob: 0.33
            mean: 0
            std: 0.1
        PatchifyLongi_our:
            keys: ['image0']
            patch_size: [16, 16, 16]
            spatial_size: [160, 240, 128]
        ToTensord_1:
            keys: ['image0', 'image1', 'image2',  'y_seq', 'rel_t']
            allow_missing_keys: True
            track_meta: False
            device: "cuda"
            dtype: bfloat16
        ToTensord_2:
            keys: ['y_mask', 't_mask']
            track_meta: False
            device: "cuda"
            dtype: bool

    dev_tf:
        LoadImaged:
            keys: ['image0', 'image1', 'image2']
            allow_missing_keys: True
        EnsureChannelFirstd:
            keys: ['image0', 'image1', 'image2']
            allow_missing_keys: True
        Resized:
            keys: ['image0', 'image1', 'image2']
            mode: ["trilinear", "trilinear", "trilinear"]
            spatial_size: [160, 240, 128]
            allow_missing_keys: True
        ToDeviced:
            keys: ['image0', 'image1', 'image2']
            device: "cuda"
        PatchifyLongi_our:
            keys: ['image0']
            patch_size: [16, 16, 16]
            spatial_size: [160, 240, 128]
        ToTensord_1:
            keys: ['image0', 'image1', 'image2',  'y_seq', 'rel_t']
            allow_missing_keys: True
            track_meta: False
            device: "cuda"
            dtype: bfloat16
        ToTensord_2:
            keys: ['y_mask', 't_mask']
            track_meta: False
            device: "cuda"
            dtype: bool

    test_tf:
        LoadImaged:
            keys: ['image0', 'image1', 'image2']
            allow_missing_keys: True
        EnsureChannelFirstd:
            keys: ['image0', 'image1', 'image2']
            allow_missing_keys: True
        Resized:
            keys: ['image0', 'image1', 'image2']
            mode: ["trilinear", "trilinear", "trilinear"]
            spatial_size: [160, 240, 128]
            allow_missing_keys: True
        PatchifyLongi_our:
            keys: ['image0']
            patch_size: [16, 16, 16]
            spatial_size: [160, 240, 128]
        ToTensord_1:
            keys: ['image0', 'image1', 'image2',  'y_seq']
            allow_missing_keys: True
            track_meta: False
            device: "cuda"
            dtype: bfloat16
        ToTensord_2:
            keys: ['y_mask', 't_mask']
            track_meta: False
            device: "cuda"
            dtype: bool
