defaults:
  - base_config
  - _self_

wandb:
    dry_run: True
    project_name: "mae-jax"
    task: "mae"
    entity: "mri-ai-lab"

data:
    dataset_file: "/mnt/nlst_data/npy/nlst_metadata_25.json"
    dataset_file_100: "/mnt/nlst_data/npy/nlst_metadata.json"
    slice_thickness_threshold: 2.5
    max_followup: 6
    num_classes: 1
    assign_splits: True
    use_thinnest_cut: True
    corrupted_paths: "./files/corrupted_img_paths.pkl"
    google_splits_filename: "./files/Shetty_et_al(Google)_data_splits.p"
    data_root: "/mnt/nlst_data/npy/"
    monai_dict_train: "/mnt/nlst_data/npy/train_vital_25.json"
    monai_dict_dev: "/mnt/nlst_data/npy/dev_vital_25.json"
    monai_dict_test: "/mnt/nlst_data/npy/test_vital_25.json"
    max_train_len: 24000
    img_size: [160, 240, 128]


training:
    dtype: bfloat16
    mask_ratio: 0.5
    seed: 0
    num_workers: 4
    dev_num_workers: 4
    test_num_workers: 1
    prefetch_factor: 8
    shuffle: True
    epochs: 1000
    batch_size: 4
    to_checkpoint: False

optimizer:
    lr_scheduler: onecycle
    peak_lr: 1.5e-4
    init_lr: 5e-5
    end_lr: 8e-6
    warmup_epochs: 50

log:
    ckpt_loc: "/mnt/external_ssd/chev/lung/vit-jax/checkpoints"
    ckpt_best: 'vit'
    ckpt_last: 'vit-last'
    ckpt_load: 'vit-last'
    checkpoint_at_epoch: 1000
    log_at_these_steps: 100
    log_scans_at_these_epochs: 5
    use_checkpoint: 'test'
    num_predictions: 20

model:
    patch_size: 16
    enc_dim: 768
    dec_dim: 768
    dropout_rate: 0.1
    enc_heads: 12
    enc_depth: 12
    dec_heads: 6
    dec_depth: 4
    in_chans: 1
    rng: 24

transform:
    train_tf:
        LoadImaged:
            keys: ['image']
            allow_missing_keys: True
        ToDeviced:
            keys: ['image']
            allow_missing_keys: True 
            device: "cuda"
        EnsureChannelFirstd:
            keys: ['image']
            allow_missing_keys: True
        Resized:
            keys: ['image']
            mode: ["trilinear"]
            spatial_size: [160, 240, 128]
            allow_missing_keys: True
        RandFlipd_1:
            keys: ['image']
            allow_missing_keys: True
            prob: 0.33
            spatial_axis: 0
        RandFlipd_2:
            keys: ['image']
            allow_missing_keys: True
            prob: 0.33
            spatial_axis: 1
        RandFlipd_3:
            keys: ['image']
            allow_missing_keys: True
            prob: 0.33
            spatial_axis: 2
        RandRotated:
            keys: ['image']
            allow_missing_keys: True
            prob: 0.5
            range_x: 0.2
            range_y: 0.2
            range_z: 0.2
            mode: ['bilinear']
        Patchify_our:
            keys: ['mask']
            patch_size: [16, 16, 16]
        ToTensord:
            keys: ['image']
            allow_missing_keys: True
            track_meta: False
            dtype: bfloat16

    dev_tf:
        LoadImaged:
            keys: ['image']
            allow_missing_keys: True
        EnsureChannelFirstd:
            keys: ['image']
            allow_missing_keys: True
        Resized:
            keys: ['image']
            mode: ["trilinear"]
            spatial_size: [160, 240, 128]
            allow_missing_keys: True
        Patchify_our:
            keys: ['mask']
            patch_size: [16, 16, 16]
        ToTensord:
            keys: ['image']
            allow_missing_keys: True
            track_meta: False
            dtype: bfloat16