wandb:
  dry_run: False
  project_name: "longitudinal_delta_training"
  task: "delta_test_inference_6"
  entity: "ge29jil-technical-university-of-munich"

data:
  features_test: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/extracted_features/registered_features/max_pool/test_reg_max_pool.pt"
  json_test: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/data/derived_datasets/test.json"
  max_seq_len: 3

model:
  input_dim: 2376 
  hidden_dim: 256 
  num_time_bins: 6
  num_heads: 4

testing:
  batch_size: 128

checkpoint_path: "/vol/miltank/projects/practical_wise2526/lung_cancer_lft/adlm_lft/longitudinal/delta/checkpoints/29-01-26_auprc_6years/best_delta_model.pt"

hydra:
  run:
    dir: .
  output_subdir: null