defaults:
  - base_config
  - _self_

wandb:
    dry_run: False
    project_name: "test-jax"
    task: "mae"
    entity: "mri-ai-lab"

data:
    dataset_file: "/dss/dssmcmlfs01/pn73mu/pn73mu-dss-0000/datasets/big_nodule_nlst/dataset_jsons/nlst_25_metadata.json"
    dataset_file_100: "/dss/dssmcmlfs01/pn73mu/pn73mu-dss-0000/datasets/big_nodule_nlst/dataset_jsons/nlst_25_metadata.json"
    slice_thickness_threshold: 2.5
    max_followup: 6
    num_classes: 1
    assign_splits: True
    use_thinnest_cut: True
    corrupted_paths: "./files/corrupted_img_paths.pkl"
    google_splits_filename: "./files/Shetty_et_al(Google)_data_splits.p"
    data_root: "/dss/dssmcmlfs01/pn73mu/pn73mu-dss-0000/datasets/big_nodule_nlst/"
    monai_dict_train: "/pool/users/braj/mae-jax/data/train_longi.json"
    monai_dict_dev: "/pool/users/braj/mae-jax/data/dev_longi.json"
    monai_dict_test: "/pool/data/lung/NLST/json/test_our.json"
    max_train_len: 24000
    img_size: [160, 240, 128]


training:
    dtype: bfloat16
    mask_ratio: 0.5
    seed: 0
    num_workers: 4
    dev_num_workers: 6
    test_num_workers: 1
    prefetch_factor: 8
    shuffle: True
    epochs: 50
    batch_size: 2
    to_checkpoint: False
    underrepresented_weight: 14

optimizer:
    lr_scheduler: onecycle
    peak_lr: 8e-6
    init_lr: 8e-6
    end_lr: 8e-6
    warmup_epochs: 0

attention:
    heads: 12
    use_cls: True
    use_mean_token: True

loss:
    sw: 10
    aw: 1

log:
    ckpt_loc: "/pool/users/braj/mae-jax/checkpoints/lungevity"
    ckpt_load_loc: "/pool/users/braj/mae-jax/checkpoints/lungevity"
    mae_ckpt_load: 'vit-last'
    mae_use_checkpoint: 'astral-plasma-71'
    ckpt_best: 'vit'
    ckpt_last: 'vit-last'
    ckpt_load: 'vit'
    use_checkpoint: 'silver-mountain-94'
    checkpoint_at_epoch: 1000
    log_at_these_steps: 2
    log_scans_at_these_epochs: 1
    num_predictions: 20
    cancer_cases_to_log: 5
    laterality_cases_to_log: 5
    healthy_cases_to_log: 5


model:
    patch_size: 16
    enc_dim: 768
    dec_dim: 768
    dropout_rate: 0.1
    enc_heads: 12
    enc_depth: 12
    dec_heads: 6
    dec_depth: 4
    in_chans: 1
    rng: 24
    fusion_layer: False

transform:
    test_tf:
        LoadImaged:
            keys: ['image', 'mask', 'annotation']
            allow_missing_keys: True
        EnsureChannelFirstd:
            keys: ['image', 'mask', 'annotation']
            allow_missing_keys: True
        ToDeviced:
            keys: ['image']
            allow_missing_keys: True 
            device: "cuda"
        Resized:
            keys: ['image', 'mask', 'annotation']
            mode: ["trilinear", "nearest", "nearest"]
            spatial_size: [160, 240, 128]
            allow_missing_keys: True
        MaskPatchesNoPopd_our:
            keys: ['mask']
            patch_size: [16, 16, 16]
            hull_only: False
            use_annotations: True
        ToTensord:
            keys: ['image']
            allow_missing_keys: True
            track_meta: False
            device: "cuda"
            dtype: bfloat16